export default {
    FETCH_CURRENCY_REQUEST: "FETCH_CURRENCY_REQUEST",
    FETCH_CURRENCY_SUCCESS: "FETCH_CURRENCY_SUCCESS",
    FETCH_CURRENCY_FAILURE: "FETCH_CURRENCY_FAILURE",

    CONVERT_CURRENCY_REQUEST: "CONVERT_CURRENCY_REQUEST",
    CONVERT_CURRENCY_SUCCESS: "CONVERT_CURRENCY_SUCCESS",
    CONVERT_CURRENCY_FAILURE: "CONVERT_CURRENCY_FAILURE",
}